---

- name: "Generating file name for load balanced record >>> {{item.host}}"
  set_fact:
    outfile: "files.output/backend-{{GSLB_DOMAIN}}/bigip-gslb-load_balanced_record.{{ item.host }}.json"

- name: "Stat file {{outfile}}"
  stat: 
    path: "{{outfile}}"
    get_checksum: no
    get_mime: no
  register: check_outfile

- name: "Generating file for load balanced record >>> {{item.host}}"
  block:
    - name: prepare the load balanced record JSON object, copy the template file
      delegate_to: localhost
      shell: |
        set -e
        cp "files.input/bigip-gslb-load_balanced_record.tmpl.json" "{{outfile}}"
    
    - name: prepare the load balanced record JSON object, parametrize the template file
      delegate_to: localhost
      replace:
        path: "{{outfile}}"
        regexp: "{{ inner.expr }}"
        replace: "{{ inner.replace }}"
      with_items:
         - { expr: '%%gslbRecord%%', replace: "{{ item.host }}" }
         - { expr: '%%gslbRecordNormalized%%', replace: "{{ item.host | regex_replace('[-.]', '_') }}" }
         - { expr: '%%poolGslbRecordNormalized%%', replace: "pool_{{ item.host | regex_replace('[-.]', '_') }}" }
      loop_control:
        loop_var: inner
  when: check_outfile.stat.exists == false

- name: "Stat file {{outfile}}.included"
  stat:
    path: "{{outfile}}.included"
    get_checksum: no
    get_mime: no
  register: check_outfile_included

- name: conditionally add load balanced record JSON document
  block:
    - name: add load balanced record to JSON document
      include_tasks: library/json-add-dict-element.yaml
      vars:
        node: "{{outfile}}"
        branch: ".{{GSLB_DOMAIN | regex_replace('[-.]', '_') }}.Application"
        leaf: ""
        base: "files.output/backend-{{GSLB_DOMAIN}}/bigip-gslb-update-config.tmpl.json"

    - name: mark file as included
      file:
        path: "{{outfile}}.included"
        state: touch
  when: check_outfile_included.stat.exists == false


