- hosts: localhost
  gather_facts: no
  vars_files:
    - "vars/credentials.yaml"
    - "vars/setup.yaml"
  roles: 
    - role: f5aas-gslb-login
    - role: f5aas-gslb-logout
#    - role: gslb-tool-verify-publicAddress



