- hosts: localhost
  gather_facts: no
  vars_files:
    - "vars/setup.yaml"
    - "vars/gslbState.uncommited.yaml"
  roles: 
    - { role: gslb-tool-eliminate-project, l7router: "{{dstOcpAlias}}" }
    - gslb-tool-populate-project


